### ISSUE TITLE
are you scut student?

### ISSUE THREAD

**Issue by youyou-an** [luoweida04/SFS#1]

**Comment by luoweida04** [comment]
yes, who are you




luo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luoweida04/SFS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月14日(星期六) 下午4:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[luoweida04/SFS] are you scut student? (Issue #1)





 
hello, are you scut student?

**Comment by youyou-an** [comment]
i am too, can i add your qq or wx?
